## <b>Data Science | Pandas</b> musobaqasidaki masalalar yechimlari

In [1]:
import pandas as pd

df = pd.read_excel('attempts.xlsx')

<b>A.</b> Pandas | Attempts | get_first_cpp

In [2]:
df[df['lang'] == 'cpp'].iloc[0]

id                                     35080
user                                Bahodir1
problem_title         Tublikga tekshirish #1
problem_difficulty                   Asoslar
lang                                     cpp
verdict                        Qabul qilindi
test_case_number                          14
time                                       1
memory                                  1608
created                  2022-01-29 09:08:43
Name: 34051, dtype: object

<b>B.</b> Pandas | Attempts | get_longest

In [3]:
df[df['user'].str.len() == df['user'].str.len().max()]['user'].values

array(['makhmadiyorovfakhriddin'], dtype=object)

<b>C.</b> Pandas | Attempts | filter_attempts_by_username

In [4]:
df[df['user'].str[0].isin(['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'])]

          id     user  ... memory              created
180      204   Alibek  ...      0  2021-02-03 14:40:11
188      214   Alibek  ...      0  2021-02-03 15:00:28
194      226   Alibek  ...      0  2021-02-03 15:15:51
198      230   Alibek  ...      0  2021-02-03 15:19:53
200      232   Alibek  ...      0  2021-02-03 15:25:54
...      ...      ...  ...    ...                  ...
68803  69927  Ozodbek  ...   6392  2022-07-22 06:58:50
68804  69928  Ozodbek  ...      0  2022-07-22 06:59:31
68805  69929  Ozodbek  ...      0  2022-07-22 07:00:40
68806  69930  Ozodbek  ...   6484  2022-07-22 07:01:33
68807  69931  Ozodbek  ...   6424  2022-07-22 07:02:12

[11586 rows x 10 columns]

<b>D.</b> Pandas | Attempts | get_even_id

In [5]:
def digits_sum(n): return 0 if n == 0 else digits_sum(n // 10) + n % 10

In [6]:
df[df['id'].apply(lambda value: digits_sum(value) % 2 == 0)]

          id                  user  ... memory              created
0          4  nazarbek_baltabaev_2  ...      0  2021-02-03 09:26:10
2          6             TimurXboy  ...      0  2021-02-03 09:26:10
4          8             TimurXboy  ...      0  2021-02-03 09:26:10
7         11    doniyor_samandarov  ...      0  2021-02-03 09:26:10
9         13    doniyor_samandarov  ...      0  2021-02-03 09:26:10
...      ...                   ...  ...    ...                  ...
68798  69922               Ozodbek  ...   6156  2022-07-22 06:38:14
68800  69924               Ozodbek  ...   6212  2022-07-22 06:53:48
68802  69926               Ozodbek  ...   6376  2022-07-22 06:58:11
68804  69928               Ozodbek  ...      0  2022-07-22 06:59:31
68807  69931               Ozodbek  ...   6424  2022-07-22 07:02:12

[34402 rows x 10 columns]

<b>E.</b> Pandas | Attempts | get_most_unaccepted_count

In [7]:
by_problem = df.groupby('problem_title')
by_problem['verdict'].apply(lambda s: 2*(s == 'Qabul qilindi').sum() < s.size).sum()

667

<b>F.</b> Pandas | Attempts | get_problems_count

In [8]:
by_problem = df.groupby('problem_title')
by_problem['lang'].apply(lambda s: (s == 'cpp').sum() >= 2).sum()

408

<b>G.</b> Pandas | Attempts | get_today_attempts

In [9]:
df[df['created'] >= '2022-07-22 00:00:00']  # 2022-07-22 o'rninga bugungi sanani yozish kerak

          id                user  ...  memory              created
68770  69894            Zohidbek  ...  132964  2022-07-22 05:25:23
68771  69895            Zohidbek  ...   57896  2022-07-22 05:26:38
68772  69896            Zohidbek  ...   73764  2022-07-22 05:28:33
68773  69897             Ozodbek  ...    6776  2022-07-22 05:36:58
68774  69898             Ozodbek  ...    6656  2022-07-22 05:39:15
68775  69899             Ozodbek  ...    6700  2022-07-22 05:40:49
68776  69900  ShukuraliDeveloper  ...    6772  2022-07-22 05:42:00
68777  69901  ShukuraliDeveloper  ...    6704  2022-07-22 05:44:22
68778  69902          Quvonchbek  ...   73480  2022-07-22 05:44:24
68779  69903             Ozodbek  ...   24048  2022-07-22 05:45:16
68780  69904  ShukuraliDeveloper  ...    6712  2022-07-22 05:48:00
68781  69905          Quvonchbek  ...   74936  2022-07-22 05:49:25
68782  69906             Ozodbek  ...    6900  2022-07-22 05:52:26
68783  69907             Ozodbek  ...    6668  2022-07-22 05:53:49
68784  69908             Ozodbek  ...    6776  2022-07-22 05:57:10
68785  69909             Ozodbek  ...    6616  2022-07-22 06:00:11
68786  69910             Ozodbek  ...    6616  2022-07-22 06:02:08
68787  69911             Ozodbek  ...    6804  2022-07-22 06:03:52
68788  69912  ShukuraliDeveloper  ...    6656  2022-07-22 06:06:10
68789  69913          Quvonchbek  ...   51912  2022-07-22 06:12:35
68790  69914             Ozodbek  ...    6748  2022-07-22 06:13:01
68791  69915             Ozodbek  ...    6828  2022-07-22 06:16:27
68792  69916             Ozodbek  ...    6680  2022-07-22 06:20:57
68793  69917             Ozodbek  ...    6792  2022-07-22 06:23:11
68794  69918             Ozodbek  ...       0  2022-07-22 06:27:13
68795  69919             Ozodbek  ...    6216  2022-07-22 06:29:38
68796  69920             Ozodbek  ...    6220  2022-07-22 06:32:57
68797  69921             Ozodbek  ...    6220  2022-07-22 06:35:41
68798  69922             Ozodbek  ...    6156  2022-07-22 06:38:14
68799  69923             Ozodbek  ...    6252  2022-07-22 06:46:37
68800  69924             Ozodbek  ...    6212  2022-07-22 06:53:48
68801  69925             Ozodbek  ...    6196  2022-07-22 06:57:37
68802  69926             Ozodbek  ...    6376  2022-07-22 06:58:11
68803  69927             Ozodbek  ...    6392  2022-07-22 06:58:50
68804  69928             Ozodbek  ...       0  2022-07-22 06:59:31
68805  69929             Ozodbek  ...       0  2022-07-22 07:00:40
68806  69930             Ozodbek  ...    6484  2022-07-22 07:01:33
68807  69931             Ozodbek  ...    6424  2022-07-22 07:02:12

[38 rows x 10 columns]

<b>H.</b> Pandas | Attempts | filter_attempts

In [10]:
import re
df[df['problem_title'].apply(lambda title: re.search(r'[^a-zA-Z][^a-zA-Z]', title) is not None)]

          id                  user  ... memory              created
56        71             bagbanpir  ...      0  2021-02-03 09:26:10
58        73               Shoxzod  ...      0  2021-02-03 09:26:10
61        76  nazarbek_baltabaev_2  ...      0  2021-02-03 09:26:10
62        77  nazarbek_baltabaev_2  ...      0  2021-02-03 09:26:10
69        84             TimurXboy  ...      0  2021-02-03 09:26:10
...      ...                   ...  ...    ...                  ...
68803  69927               Ozodbek  ...   6392  2022-07-22 06:58:50
68804  69928               Ozodbek  ...      0  2022-07-22 06:59:31
68805  69929               Ozodbek  ...      0  2022-07-22 07:00:40
68806  69930               Ozodbek  ...   6484  2022-07-22 07:01:33
68807  69931               Ozodbek  ...   6424  2022-07-22 07:02:12

[43747 rows x 10 columns]

<b>I.</b> Pandas | Attempts | get_users_solved

In [11]:
by_solved_user = df[df['verdict'] == 'Qabul qilindi'].drop_duplicates(['user', 'problem_title']).groupby('user')
by_solved_user['id'].count().sort_values()

user
cholpan135_97        1
cholpan135_40        1
cholpan135_4         1
cholpan135_39        1
cholpan135_38        1
                  ...
temur.dusenbaev    528
Zohidbek           552
The_Samurai        650
Quvonchbek         665
Narzullayev.S_     749
Name: id, Length: 600, dtype: int64

<b>J.</b> Pandas | Attempts | get_users_rating

In [12]:
by_solved_user = df[df['verdict'] == 'Qabul qilindi'].drop_duplicates(['user', 'problem_title']).groupby('user')

balls = {
    'Boshlangich': 1,
    'Asoslar': 2,
    'Normal': 3,
    "O'rtacha": 4,
    "Ilg'or": 5,
    'Qiyin': 6,
}

by_solved_user['problem_difficulty'].apply(lambda s: s.apply(lambda value: balls[value]).sum()).sort_values()

user
cholpan_sql2         1
cholpan168_1         1
cholpan168_0         1
cholpan33            1
cholpan34            1
                  ...
Zohidbek          1429
Dasturchi         1534
Quvonchbek        1867
The_Samurai       1919
Narzullayev.S_    2115
Name: problem_difficulty, Length: 600, dtype: int64